sudo: required

services:
  - docker

script:
  - ./scripts/build-docker.sh

after_success:
#  - set -e
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker push 
    fi